// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {instances} from '../models';
import {mode} from '../models';

export function CreateInstance(arg1:instances.Instance):Promise<instances.Instance>;

export function DeleteInstance(arg1:string):Promise<string>;

export function Install(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function JitsiHosts():Promise<Array<string>>;

export function ListInstances():Promise<Array<instances.Instance>>;

export function Mode():Promise<mode.Mode>;

export function TestRoom(arg1:string,arg2:string,arg3:string):Promise<string>;
