// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateInstance(arg1) {
  return window['go']['panel']['API']['CreateInstance'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['panel']['API']['DeleteInstance'](arg1);
}

export function Install(arg1, arg2, arg3, arg4) {
  return window['go']['panel']['API']['Install'](arg1, arg2, arg3, arg4);
}

export function JitsiHosts() {
  return window['go']['panel']['API']['JitsiHosts']();
}

export function ListInstances() {
  return window['go']['panel']['API']['ListInstances']();
}

export function Mode() {
  return window['go']['panel']['API']['Mode']();
}

export function TestRoom(arg1, arg2, arg3) {
  return window['go']['panel']['API']['TestRoom'](arg1, arg2, arg3);
}
